---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull srijanprakash/calculator
      
    - name: running container
      shell: docker run -it -d srijanprakash/calculator /bin/bash

    
